M48
; DRILL file {KiCad 9.0.6} date 2026-03-17T21:12:54+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-17T21:12:54+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T1
X173.45Y-97.375
X173.45Y-102.375
T2
X134.0Y-85.0
X134.0Y-117.975
X175.5Y-85.0
X175.5Y-118.0
M30
